blank_issues_enabled: true
contact_links:
  - name: Overcast Community Discord
    url: https://oc.tc/discord
    about: For additional help involving maps, join the Discord and visit the `#mapmaking` channel.