name: Contest Submission
description: 'Submit a map to Overcast Community for the TNT Mapmaking Contest.'
title: '[GAMEMODE/SIZE] Map Name'
labels:
  - contest
  - map
  - submission
body:
  - type: checkboxes
    id: map-checklist
    attributes:
      label: Checklist
      description: Check what applies to you.
      options:
        - label: >-
            I have
            [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the
            map.
          required: false
        - label: >-
            I have agreed with assigning the CC BY-SA license to this map, as
            mentioned in the
            [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
          required: false
        - label: >-
            I have read and understood the 
            [map submission guidelines](https://oc.tc/submissions).
          required: false
        - label: I have created an XML file.
          required: false
        - label: I have created a map image.
          required: false
        - label: I have uploaded the map zip file to a file sharing service.
          required: false
        - label: The map has been tested locally to make sure it works.
          required: false
  - type: input
    id: map-name
    attributes:
      label: Map Name
      description: What is the map called?
    validations:
      required: true
  - type: textarea
    id: map-description
    attributes:
      label: Gamemode & Map Description
      description: >-
        What gamemode(s) do your map use? Also provide a small description of
        the map and how you envision it playing.
    validations:
      required: true
  - type: input
    id: map-team-size
    attributes:
      label: Team Sizes
      description: How many teams and how large are they?
    validations:
      required: true
  - type: input
    id: map-screenshot-album
    attributes:
      label: Screenshots
      description: >-
        Create an album on [Imgur](https://imgur.com) with screenshots of the
        map and link it here. Try to include at least one screenshot showing the
        entire map as a whole, from above, if possible.
  - type: input
    id: map-xml
    attributes:
      label: XML
      description: >-
        Please
        [make](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#the-maps-xml-file)
        an `map.xml` file for your map and upload it to https://gist.github.com
        and link it here.
    validations:
      required: true
  - type: textarea
    id: map-image
    attributes:
      label: Map Image
      description: >-
        Please attempt to
        [make](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#the-map-image)
        a nice `map.png` in `290x246` resolution without any resource pack or
        shaders enabled. Upload it by dragging it (or copying and pasting with
        `Ctrl` + `C` and `Ctrl` + `V`) into the text box below.
    validations:
      required: true
  - type: textarea
    id: map-download
    attributes:
      label: Map Download
      description: >-
        [Package the
        map](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#compressing-the-folder-to-a-zip-file)
        and upload it somewhere where we can download it, like **Google Drive**,
        **Dropbox**, or by dragging it into this text box. Make sure your file
        contains a `region` folder, a `level.dat`, a `map.xml`, and a `map.png`.
    validations:
      required: true
