name: Map Update
description: 'Update a pre-existing map on the CommunityMaps repository.'
title: '[Update] Map Name, Version'
labels:
  - map
  - update
body:
  - type: checkboxes
    id: map-checklist
    attributes:
      label: Checklist
      description: Check what applies to you.
      options:
        - label: >-
            The updated map files are
            [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or
            the update is XML only.
          required: false
        - label: I have uploaded the map zip file to a file sharing service.
          required: false
        - label: The update has been tested locally to make sure it works.
          required: false
  - type: textarea
    id: map-changes
    attributes:
      label: Changes
      description: Please provide a short summary of changes to the map.
    validations:
      required: true
  - type: input
    id: map-xml
    attributes:
      label: XML
      description: >-
        Please
        [make](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#the-maps-xml-file)
        an `map.xml` file for your map and upload it to https://gist.github.com
        and link it here.
    validations:
      required: true
  - type: input
    id: map-download
    attributes:
      label: Download Link
      description: >-
        [Package the
        map](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#compressing-the-folder-to-a-zip-file)
        and upload it somewhere where we can download it, like **Google Drive**,
        **Dropbox**, or by dragging it into this text box. Make sure your file
        contains a `region` folder, a `level.dat`, a `map.xml`, and a `map.png`.
    validations:
      required: true